<?php

    function dna_module_menu() {
        $items = array();
        $items['dna_module'] = array(
            'title' => 'DNA Module',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('dna_module_form'),
        );
        $items['dna_success'] = array(
            'title' => 'DNA Module Success',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'dna_module_success',
        );
        return $items;
    }

    function dna_module_form() {
        $form = array();
        $form['input'] = array(
            '#title' => 'Input',
            '#type' => 'textfield',
            '#description' => t('Please enter your nuceleotide sequence!'),
            '#element_validate' => array('element_validate_letters'),
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Double helix me!'
        );
        return $form;
    }


    function element_validate_letters($element) {
        $input_string = strtolower($element['#value']);
        $exploded_string = str_split($input_string);
        foreach ($exploded_string as $letter) {
            if ($letter != 'a' && $letter != 't' && $letter != 'c' && $letter != 'g') {
                form_error($element, t("Please only use the letters 'a', 't', 'c', and 'g'."));
            }
        }
    }

    function make_dna($input) {
        $exploded_string = str_split($input);

        $result =  array();
        foreach($exploded_string as $letter) {
            if (strtolower($letter) == 'a') {
                array_push($result, 't');
            }
            if (strtolower($letter) == 't') {
                array_push($result, 'a');
            }
            if (strtolower($letter) == 'c') {
                array_push($result, 'g');
            }
            if (strtolower($letter) == 'g') {
                array_push($result, 'c');
            }
        }

        $result = implode(" ", $result);
        return $result;
    }

    function dna_module_form_submit($form, &$form_state) {
        $input = $form_state['values']['input'];

        $result = make_dna($input);

        $_SESSION['dna_module_input_array'] = str_split($input);
        $_SESSION['dna_module_output'] = $result;
        $form_state['redirect'] = 'dna_success';
    }

    function dna_module_success() {
        $input = implode(" ", $_SESSION['dna_module_input_array']);
        $results = $_SESSION['dna_module_output'];
        return '<div>' . $input . '</div>' . '<div>' . $results . '</div>';
}
